### ISSUE TITLE
Add support for TrackJS, JavaScript error tracking

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#47]
They're willing to sponsor us since we're open source.

- [x] Create a trial account
- [x] Get a token
- [x] Add token
- [x] Add the dependency (`bower install --save trackjs`)
- [x] After 30 days if it's useful, email the team for an account upgrade

**Comment by shakeelmohamed** [comment]
All done thanks to @thomasjosephgreco with #86!
